[package]
name = "chapter_8"
version = "0.1.0"
edition = "2021"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[dependencies]
libc = "0.2"
